# Generated by Django 4.2.1 on 2023-05-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListarTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarefa', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=45)),
                ('data_criacao', models.DateField()),
            ],
        ),
    ]
