# Generated by Django 4.2.1 on 2023-06-01 18:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0002_rename_nome_tarefa_listartarefa_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('idade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('email', models.EmailField(max_length=254)),
                ('tarefa', models.CharField(max_length=50)),
                ('senha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefa.listartarefa')),
            ],
        ),
    ]
