# Generated by Django 4.2.1 on 2023-06-01 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0003_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefa.listartarefa'),
        ),
    ]
