# Generated by Django 4.2.1 on 2023-06-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0005_tasksusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tarefa',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tarefa',
            field=models.ManyToManyField(related_name='usuarios', to='tarefa.listartarefa'),
        ),
    ]
