# Generated by Django 4.2.1 on 2023-06-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0006_remove_usuario_tarefa_usuario_tarefa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksusuario',
            old_name='tarefas',
            new_name='tasks',
        ),
        migrations.AddField(
            model_name='listartarefa',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
