# Generated by Django 4.2.1 on 2023-06-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0007_rename_tarefas_tasksusuario_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksusuario',
            name='tasks',
        ),
    ]
