# Generated by Django 4.2.1 on 2023-06-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0009_listartarefa_vencimento_tasksusuario_tarefa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TasksUsuario',
        ),
    ]
